import { Inter } from "next/font/google";
//import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import Menu from "@/components/client/menu";
import AuthProvider from "@/providers/authProvider";
import SideBar from "@/components/admin/sideBar";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//children c'est la page.js
export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
if (!session) {
return (
<section className='py-24'>
<div className='container'>
<h1 className='text-2xl font-bold'>
You are not authorized to view this page
</h1>
</div>
</section>
)
}
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SideBar/>
        <Menu/>
        </AuthProvider>
        {children}</body>
    </html>
  );
}
